# config/routes.yaml

index:
  path: /
  defaults: { _controller: 'App\Controller\CoursController::index' }

registration_register:
  path: /security/inscription
  defaults: { _controller: 'App\Controller\RegistrationController::register' }

login:
  path: /security/login
  defaults: { _controller: 'App\Controller\SecurityController::login' }

cours_show:
  path: /cours/{id_cours}
  defaults: { _controller: 'App\Controller\CoursController::show' }
  requirements:
    id_courrs: '\d+'


