# config/routes.yaml

index:
  path: /
  defaults: { _controller: 'App\Controller\CoursController::index' }

utilisateur_new:
  path: /utilisateur/inscription
  defaults: { _controller: 'App\Controller\UtilisateurController::new' }


# Depends on sensio/framework-extra-bundle, doctrine/annotations, and doctrine/cache
#   install with composer req sensio/framework-extra-bundle annot
#controllers:
#    resource: ../src/Controller/
#    type: annotation